name: Build & Deploy MkDocs (gh-pages with PR previews)

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, closed]
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install '.[docs]'
      - name: Build with MkDocs
        run: mkdocs build
      - name: Upload built site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./site

  deploy:
    needs: build
    # Deploy on:
    # - push to main (production to root), or
    # - pull_request (not closed) from same repo (preview to pr-<N>/)
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' &&
       github.event.action != 'closed' &&
       github.event.pull_request.head.repo.fork == false)
    runs-on: ubuntu-latest
    steps:
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: ./site

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          keep_files: true
          # PRs go to gh-pages/pr-<number>/ ; pushes to main go to root
          destination_dir: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || '' }}

  cleanup:
  # Just when a PR is closed (merged or without merge)
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Remove preview folder
        shell: bash
        run: |
          set -e
          PR_DIR="pr-${{ github.event.number }}"
          if [ -d "$PR_DIR" ]; then
            git rm -r "$PR_DIR"
            git commit -m "Remove preview for PR #${{ github.event.number }}"
            git push origin gh-pages
          else
            echo "No preview folder $PR_DIR found; nothing to do."
          fi
