name: windows test

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        python -m pip install hatchling 
        python -m pip install --no-build-isolation .
    - name: Running unit tests
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN_TESTING }}
      run: |
        python -m unittest tests/test_cvat2slowfast.py
        # python -m unittest tests/test_cvat2ultralytics.py
        # python -m unittest tests/test_detector2cvat.py
        # python -m unittest tests/test_miniscene2behavior.py
        # python -m unittest tests/test_player.py
        # python -m unittest tests/test_tracks_extractor.py
